import { person } from "./person";
import { photo } from "./photo";

export interface fullPersonInfo {
    version: number;
    person: person;
    studyLanguage: string;
    curriculumSpeciality: string | null;
    speciality: string | null;
    addSpecialityEt: string | null;
    addSpecialityEn: string | null;
    curriculumStudyField: string | null;
    nominalStudyEnd: string;
    finSpecific: string;
    schoolEmail: string;
    previousStudyLevel: string;
    studyCompany: string | null;
    previousSchoolName: string;
    previousSchoolEndDate: string;
    dormitory: string;
    secondarySchoolCountry: string | null;
    isSpecialNeed: boolean;
    specialNeed: string | null;
    specialNeeds: string[];
    isRepresentativeMandatory: boolean;
    photo: photo;
    deleteCurrentPhoto: any;
    job: string | null;
    jobOccupation: string | null;
    otherContact: any;
    isAcadStudyAllowed: boolean;
    representativeOtherContact: any;
    studentLanguages: any[];
    occupationCertificates: any[];
    minorSpecialities: any;
    id: number;
    school: {
        id: number;
        nameEt: string;
        nameEn: string;
        nameRu: string;
    };
    status: string;
    curriculum: number;
    curriculumVersion: {
        id: number;
        nameEt: string;
        nameEn: string;
        code: string;
        curriculum: number;
        schoolDepartment: any;
        studyForm: any;
        isVocational: boolean;
        isHigher: boolean;
        isSecondary: boolean;
        isBasic: boolean;
        isFictive: any;
        studyLang: any;
        specialities: any;
        studyField: any;
        nameRu: string;
    };
    curriculumObject: {
        id: number;
        nameEt: string;
        nameEn: string;
        nameRu: string;
    };
    studentGroup: {
        id: number;
        nameEt: string;
        nameEn: string;
        nameRu: string;
    };
    course: number;
    studentCard: any;
    studentCardStatus: string;
    studentCardValidThru: any;
    studentCardGivenDt: any;
    studentCardReturnedDt: any;
    isStudentCardRepetitive: any;
    studyStart: string;
    studyEnd: any;
    studyForm: string;
    studyLoad: string;
    studyLevel: string;
    fin: string;
    isHigher: boolean;
    isVocational: boolean;
    isBasic: boolean;
    isSecondary: boolean;
    userCanEditStudent: boolean;
    userCanAddRepresentative: boolean;
    userIsStudentGroupTeacher: boolean;
    userCanViewStudentSpecificData: boolean;
    userCanUpdateRR: boolean;
    userCanRequestPhotoBoxPhoto: boolean;
    userCanViewStudentSupportServices: boolean;
    userCanViewPrivateStudentSupportServices: boolean;
    userCanViewStudentAddInfo: boolean;
    studentCanAddPhoto: boolean;
    isGuestStudent: boolean;
    curriculumCredits: number;
    credits: number;
    averageMark: number;
    apelApplicationCredits: number;
    isCurriculumFulfilled: boolean;
    curriculumIncludesSpecialities: boolean;
    hasRemarksPastSevenDays: boolean;
    individualCurriculum: boolean;
    individualCurriculumStart: any;
    individualCurriculumEnd: any;
    boardingSchool: any;
    boardingSchoolValidFrom: any;
    boardingSchoolValidThru: any;
    boardingSchoolAddInfo: any;
    type: string;
    fulfillmentPercentage: number;
    addInfo: any;
    regNr: number;
    whiteCertificate: any;
    dormitoryHistory: {
        date: string;
        dormitory: string;
    }[];
}
